### ISSUE TITLE
(IMPORT FAILED): 缺少__init__.py文件

### ISSUE THREAD

**Issue by markawonge** [laojingwei/comfy_Translation#1]
OS：Linux(ubuntu 22.04 LTS / 23.04 / Fedora 38)
环境：miniconda
终端提示如下：
Traceback (most recent call last):
  File "/home/kwan/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/kwan/ComfyUI/custom_nodes/comfy_Translation/__init__.py'

Cannot import /home/kwan/ComfyUI/custom_nodes/comfy_Translation module for custom nodes: [Errno 2] No such file or directory: '/home/kwan/ComfyUI/custom_nodes/comfy_Translation/__init__.py'

**Comment by laojingwei** [comment]
我去看了下启动comfy_Translation是可以的，要不你试试使用这个吧，https://github.com/laojingwei/comfy_translation_node
这个比较好，comfy_Translation不建议使用了，目前有道翻译api好像不给使用了，没法翻译，可以选择谷歌的api，如果你真想用comfy_Translation可以新建一个comfy_Translation文件夹，然后把comfy_Translation.py改为init.py放进去
